version: 1
labels:
  - label: "priority:p0"
    body: "(### Severity\n\nCritical)|(- \[x] Critical)"
  - label: "priority:p1"
    body: "(### (Priority|Severity)\n\nHigh)|(- \[x] High)"
  - label: "priority:p2"
    body: "(### (Priority|Severity)\n\nMedium)|(- \[x] Medium)"
  - label: "priority:p3"
    body: "(### (Priority|Severity)\n\nLow)|(- \[x] Low)"
  - label: "pr:type:feat"
    type: "pull_request"
    body: "- \[x] Feature"
  - label: "pr:type:feat"
    type: "pull_request"
    title: "^feat:.*"
  - label: "pr:type:fix"
    type: "pull_request"
    body: "- \[x] Bug fix"
  - label: "pr:type:fix"
    type: "pull_request"
    title: "^fix:.*"
  - label: "affects:documentation"
    body: "(- \[x] Documentation only|\bdoc[s]\b|\bdocumentation[s]\b)"
  - label: "affects:functionality"
    body: "\bfunctionalit(?:y|ies)\b"
  - label: "affects:locale"
    body: "(\blocale[s]?\b|\blocali(?:s|z)(?:e[d]?|ation)\b)"
  - label: "affects:locale"
    files:
      - "\\/locales\\/.*"
  - label: "affects:permissions"
    body: "\bpermission[s]?\b"
  - label: "branch:stable"
    type: "issue"
    body: "- \[x] Stable"
  - label: "branch:next"
    type: "issue"
    body: "- \[x] Next"
