project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /locales/en/*.js
    translation: /locales/%two_letters_code%/%original_file_name%

preserve_hierarchy: true
