export enum PlayerResponse {
    RestartInProgress,
    FeatureDisabled,
    FeatureNotWhitelisted,
    FeatureConflict,
    QueueChannelMissing,
    InsufficientPermissions,
    QueueInsufficientTracks,
    InputOutOfRange,
    InputInvalid,
    PlayerStateUnchanged,
    PlayerIdle,
    PlayerIsStream,
    Success,
}
