name: Bug report
description: Something not working as intended, or affecting normal functionality.
labels: [ 'type:bug' ]
type: Bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: What isn't working as intended, and what does it affect?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Severity
      description: The severity of the issue.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Affected branches
      description: Does the issue affect the stable version, development version, or both?
      options:
        - label: Stable
        - label: Next
  - type: input
    attributes:
      label: Quaver version
      description: The version of Quaver you were using when experiencing this issue.
      placeholder: 6.8.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: click on a button, enter a value, etc. and see error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What is expected to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happens? Attach or add errors or screenshots here as well.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
