name: Labeler
on:
  issues:
    types: [ opened, edited ]
  pull_request_target:
    types: [ opened, edited ]

jobs:
  labeler:
    name: Assign Labels
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Assign Labels
        uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
