name: Update staging branch
on:
  workflow_run:
    workflows: [ Release ]
    types: [ completed ]
    branches: [ master ]

permissions:
  contents: write

jobs:
  update-staging:
    name: Sync staging with master
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - name: Merge changes from 'master' into 'staging'
        run: |
          git checkout master
          git fetch origin
          git checkout staging
          git pull
          git merge origin/master
          git push origin staging