name: Update next branch
on:
  workflow_run:
    workflows: [ Release ]
    types: [ completed ]
    branches: [ staging ]

permissions:
  contents: write

jobs:
  update-next:
    name: Sync next with staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - name: Merge changes from 'staging' into 'next'
        run: |
          git checkout staging
          git fetch origin
          git checkout next
          git pull
          git merge origin/staging
          git push origin next